"""25032025

Revision ID: 0efa7cc968ba
Revises: 4c225b605985
Create Date: 2025-03-25 18:19:08.525909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efa7cc968ba'
down_revision = '4c225b605985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('foreign_currency', sa.String(length=4), nullable=True),
    sa.Column('local_currency', sa.String(length=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchanges_id'), 'exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_exchanges_name'), 'exchanges', ['name'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.create_table('shippingorders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('shipping_name', sa.String(length=255), nullable=False),
    sa.Column('shipping_phone_number', sa.String(length=13), nullable=False),
    sa.Column('send_store_id', sa.UUID(), nullable=True),
    sa.Column('receive_store_id', sa.UUID(), nullable=True),
    sa.Column('shipping_status', sa.Integer(), nullable=False),
    sa.Column('store_status', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('wide', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('weight_packaged', sa.Float(), nullable=False),
    sa.Column('height_packaged', sa.Float(), nullable=False),
    sa.Column('wide_packaged', sa.Float(), nullable=False),
    sa.Column('length_packaged', sa.Float(), nullable=False),
    sa.Column('wood_packaged_fee', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receive_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['send_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shippingorders_id'), 'shippingorders', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_plan_id'), 'accounts', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_plan_id'), table_name='accounts')
    op.drop_index(op.f('ix_shippingorders_id'), table_name='shippingorders')
    op.drop_table('shippingorders')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_exchanges_name'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_id'), table_name='exchanges')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
