"""consignment_foreign_shipment_codes

Revision ID: 27f9ecfbb569
Revises: 58c108ae0077
Create Date: 2025-04-06 01:32:10.471659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f9ecfbb569'
down_revision = '58c108ae0077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consignment_foreign_shipment_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consignment_id', sa.Integer(), nullable=False),
    sa.Column('foreign_shipment_code', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['consignment_id'], ['consignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consignment_foreign_shipment_codes_consignment_id'), 'consignment_foreign_shipment_codes', ['consignment_id'], unique=False)
    op.create_index(op.f('ix_consignment_foreign_shipment_codes_foreign_shipment_code'), 'consignment_foreign_shipment_codes', ['foreign_shipment_code'], unique=False)
    op.create_index(op.f('ix_consignment_foreign_shipment_codes_id'), 'consignment_foreign_shipment_codes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consignment_foreign_shipment_codes_id'), table_name='consignment_foreign_shipment_codes')
    op.drop_index(op.f('ix_consignment_foreign_shipment_codes_foreign_shipment_code'), table_name='consignment_foreign_shipment_codes')
    op.drop_index(op.f('ix_consignment_foreign_shipment_codes_consignment_id'), table_name='consignment_foreign_shipment_codes')
    op.drop_table('consignment_foreign_shipment_codes')
    # ### end Alembic commands ###
