"""adding user_finance

Revision ID: 2becf22756a0
Revises: 7e0c0e82e58b
Create Date: 2025-04-17 10:48:22.980193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2becf22756a0'
down_revision = '7e0c0e82e58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_finances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_finances_created_at'), 'user_finances', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_finances_id'), 'user_finances', ['id'], unique=False)
    op.create_index(op.f('ix_user_finances_updated_at'), 'user_finances', ['updated_at'], unique=False)
    op.add_column('deposit_bills', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('deposit_bills', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('deposit_bills', 'user_fullname',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('deposit_bills', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('deposit_bills', 'deposit_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_deposit_bills_updated_at'), 'deposit_bills', ['updated_at'], unique=False)
    op.add_column('shipments', sa.Column('shipping_fee', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'shipping_fee')
    op.drop_index(op.f('ix_deposit_bills_updated_at'), table_name='deposit_bills')
    op.alter_column('deposit_bills', 'deposit_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('deposit_bills', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('deposit_bills', 'user_fullname',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('deposit_bills', 'updated_at')
    op.drop_column('deposit_bills', 'status')
    op.drop_index(op.f('ix_user_finances_updated_at'), table_name='user_finances')
    op.drop_index(op.f('ix_user_finances_id'), table_name='user_finances')
    op.drop_index(op.f('ix_user_finances_created_at'), table_name='user_finances')
    op.drop_table('user_finances')
    # ### end Alembic commands ###
