"""change shipment's shipping fee name

Revision ID: 36b918ec4ac4
Revises: 2becf22756a0
Create Date: 2025-04-17 11:44:39.169820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b918ec4ac4'
down_revision = '2becf22756a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('domestic_shipping_fee', sa.Float(), nullable=False))
    op.drop_column('shipments', 'shipping_fee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('shipping_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('shipments', 'domestic_shipping_fee')
    # ### end Alembic commands ###
