"""28032025

Revision ID: 4f5bc3a0971b
Revises: 0efa7cc968ba
Create Date: 2025-03-28 09:13:00.538169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5bc3a0971b'
down_revision = '0efa7cc968ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category_parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.add_column('shipping_orders', sa.Column('shipping_address', sa.String(length=2056), nullable=False))
    op.add_column('shipping_orders', sa.Column('contains_liquid', sa.Boolean(), nullable=False))
    op.add_column('shipping_orders', sa.Column('is_fragile', sa.Boolean(), nullable=False))
    op.add_column('shipping_orders', sa.Column('wooden_packaging_required', sa.Boolean(), nullable=False))
    op.add_column('shipping_orders', sa.Column('insurance_required', sa.Boolean(), nullable=False))
    op.add_column('shipping_orders', sa.Column('item_count_check_required', sa.Boolean(), nullable=False))
    op.add_column('shipping_orders', sa.Column('contains_liquid_fee', sa.Float(), nullable=False))
    op.add_column('shipping_orders', sa.Column('is_fragile_fee', sa.Float(), nullable=False))
    op.add_column('shipping_orders', sa.Column('wooden_packaging_required_fee', sa.Float(), nullable=False))
    op.add_column('shipping_orders', sa.Column('insurance_required_fee', sa.Float(), nullable=False))
    op.add_column('shipping_orders', sa.Column('item_count_check_required_fee', sa.Float(), nullable=False))
    op.add_column('shipping_orders', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.drop_column('shipping_orders', 'wood_packaged_fee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.add_column('shipping_orders', sa.Column('wood_packaged_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('shipping_orders', 'image_path')
    op.drop_column('shipping_orders', 'item_count_check_required_fee')
    op.drop_column('shipping_orders', 'insurance_required_fee')
    op.drop_column('shipping_orders', 'wooden_packaging_required_fee')
    op.drop_column('shipping_orders', 'is_fragile_fee')
    op.drop_column('shipping_orders', 'contains_liquid_fee')
    op.drop_column('shipping_orders', 'item_count_check_required')
    op.drop_column('shipping_orders', 'insurance_required')
    op.drop_column('shipping_orders', 'wooden_packaging_required')
    op.drop_column('shipping_orders', 'is_fragile')
    op.drop_column('shipping_orders', 'contains_liquid')
    op.drop_column('shipping_orders', 'shipping_address')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
