"""adding store's fields

Revision ID: 6d5605dbd0f7
Revises: 27f9ecfbb569
Create Date: 2025-04-09 18:52:49.152622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5605dbd0f7'
down_revision = '27f9ecfbb569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consignments', sa.Column('source_store_id', sa.Integer(), nullable=False))
    op.add_column('consignments', sa.Column('dest_store_id', sa.Integer(), nullable=False))
    op.alter_column('consignments', 'code',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('ix_consignments_store_id', table_name='consignments')
    op.create_index(op.f('ix_consignments_dest_store_id'), 'consignments', ['dest_store_id'], unique=False)
    op.create_index(op.f('ix_consignments_source_store_id'), 'consignments', ['source_store_id'], unique=False)
    op.drop_constraint('consignments_store_id_fkey', 'consignments', type_='foreignkey')
    op.create_foreign_key(None, 'consignments', 'stores', ['dest_store_id'], ['id'])
    op.create_foreign_key(None, 'consignments', 'stores', ['source_store_id'], ['id'])
    op.drop_column('consignments', 'store_id')
    op.add_column('stores', sa.Column('type_store', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('code', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'stores', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_constraint(None, 'stores', type_='unique')
    op.drop_column('stores', 'code')
    op.drop_column('stores', 'type_store')
    op.alter_column('product_categories', 'category_parent_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.add_column('consignments', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'consignments', type_='foreignkey')
    op.drop_constraint(None, 'consignments', type_='foreignkey')
    op.create_foreign_key('consignments_store_id_fkey', 'consignments', 'stores', ['store_id'], ['id'])
    op.drop_index(op.f('ix_consignments_source_store_id'), table_name='consignments')
    op.drop_index(op.f('ix_consignments_dest_store_id'), table_name='consignments')
    op.create_index('ix_consignments_store_id', 'consignments', ['store_id'], unique=False)
    op.alter_column('consignments', 'code',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('consignments', 'dest_store_id')
    op.drop_column('consignments', 'source_store_id')
    # ### end Alembic commands ###
