"""add consignment's note

Revision ID: 774318efc52b
Revises: b99c29024f1a
Create Date: 2025-04-18 10:25:54.358752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774318efc52b'
down_revision = 'b99c29024f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consignments', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consignments', 'note')
    # ### end Alembic commands ###
