"""adding change_logs features

Revision ID: a16d8072094e
Revises: 6d5605dbd0f7
Create Date: 2025-04-11 23:32:34.466949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16d8072094e'
down_revision = '6d5605dbd0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_logs_object_id'), 'change_logs', ['object_id'], unique=False)
    op.create_index(op.f('ix_change_logs_user_id'), 'change_logs', ['user_id'], unique=False)
    op.create_index('ix_object_type_object_id', 'change_logs', ['object_type', 'object_id'], unique=False)
    op.create_index('ix_user_id_object_type', 'change_logs', ['user_id', 'object_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_id_object_type', table_name='change_logs')
    op.drop_index('ix_object_type_object_id', table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_user_id'), table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_object_id'), table_name='change_logs')
    op.drop_table('change_logs')
    # ### end Alembic commands ###
