"""Add user_id to fulfillment

Revision ID: b5420e5b19db
Revises: c610161ac26a
Create Date: 2025-05-20 00:30:16.329786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5420e5b19db'
down_revision = 'c610161ac26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fulfillments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fulfillments', 'users', ['user_id'], ['id'])
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_constraint(None, 'fulfillments', type_='foreignkey')
    op.drop_column('fulfillments', 'user_id')
    # ### end Alembic commands ###
