"""Add user_id to shipment

Revision ID: c610161ac26a
Revises: 774318efc52b
Create Date: 2025-05-19 23:28:01.465391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c610161ac26a'
down_revision = '774318efc52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shipments', 'users', ['user_id'], ['id'])
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'user_id')
    # ### end Alembic commands ###
