"""update some business logic for finance

Revision ID: decaf7e9d344
Revises: 36b918ec4ac4
Create Date: 2025-04-17 18:09:23.478877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decaf7e9d344'
down_revision = '36b918ec4ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('weight', sa.Float(), nullable=False))
    op.add_column('shipments', sa.Column('height', sa.Float(), nullable=False))
    op.add_column('shipments', sa.Column('wide', sa.Float(), nullable=False))
    op.add_column('shipments', sa.Column('length', sa.Float(), nullable=False))
    op.add_column('shipments', sa.Column('weight_packaged', sa.Float(), nullable=False))
    op.add_column('shipments', sa.Column('height_packaged', sa.Float(), nullable=False))
    op.add_column('shipments', sa.Column('wide_packaged', sa.Float(), nullable=False))
    op.add_column('shipments', sa.Column('length_packaged', sa.Float(), nullable=False))
    op.create_index(op.f('ix_shipments_code'), 'shipments', ['code'], unique=False)
    op.add_column('stores', sa.Column('base_fee', sa.Float(), nullable=True))
    op.alter_column('users', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('stores', 'base_fee')
    op.drop_index(op.f('ix_shipments_code'), table_name='shipments')
    op.drop_column('shipments', 'length_packaged')
    op.drop_column('shipments', 'wide_packaged')
    op.drop_column('shipments', 'height_packaged')
    op.drop_column('shipments', 'weight_packaged')
    op.drop_column('shipments', 'length')
    op.drop_column('shipments', 'wide')
    op.drop_column('shipments', 'height')
    op.drop_column('shipments', 'weight')
    # ### end Alembic commands ###
